---
title: "Bayesian modelling"
author: "Paul V"
date: "27/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Libraries
```{r, message = FALSE}
library(tidyverse)
library(data.table)
library(psych)
library(standardize)
library(gridExtra)
library(corrplot)
library(GPArotation)
library(RColorBrewer)
library(lubridate)
library(vroom)
library(fasttime)
library(sjPlot)
library(naniar)
library(nFactors)
library(TTR)
library(tidyquant)
library(lme4)
library(apaTables)
library(rethinking)
```

## Data set-up
```{r}
setwd("E:/R files")
#For Laptop work setwd("/home/vanagpau/R/thermostat")
#Load Values and Environmental Behaviours (VEB) Questionnaire
VEB <- fread ("VEB.csv")
as_tibble (VEB)


#Create filter for all completed and non-preview surveys: cs ('completed surveys')
cs <- VEB %>% filter(Status == "IP Address", Progress == "100")
  
#Replace Likert strings with numbers as characters
cs <- cs %>% lapply(gsub, pattern = "Strongly agree", replacement = 3)
cs <- cs %>% lapply(gsub, pattern = "Agree", replacement = 2)
cs <- cs %>% lapply(gsub, pattern = "Somewhat agree", replacement = 1)
cs <- cs %>% lapply(gsub, pattern = "Neither agree nor disagree", replacement = 0)
cs <- cs %>% lapply(gsub, pattern = "Somewhat disagree", replacement = -1)
cs <- cs %>% lapply(gsub, pattern = "Disagree", replacement = -2)
cs <- cs %>% lapply(gsub, pattern = "Strongly disagree", replacement = -3)
cs <- cs %>% lapply(gsub, pattern = "7 = Very likely", replacement = 7)
cs <- cs %>% lapply(gsub, pattern = "4 = Neither likely nor unlikely", replacement = 4)
cs <- cs %>% lapply(gsub, pattern = "1 = Not at all likely", replacement = 1)
cs <- cs %>% lapply(gsub, pattern = "5 = Very much", replacement = 5)
cs <- cs %>% lapply(gsub, pattern = "1 = Not at all", replacement = 1)
cs <- cs %>% lapply(gsub, pattern = "1 = Very conservative", replacement = 1)
cs <- cs %>% lapply(gsub, pattern = "7 = Very liberal", replacement = 7)

#Convert Crescent & Warneford to characters
cs$Q3 <- as.character(cs$Q3)

#Convert Age data to numeric
cs$Q34 <- as.numeric(cs$Q34)

#Coerce list back to tibble
cs <- as_tibble(cs)

#Rename halls to match with thermostat data
cs[cs$Q3 == "Crescent Hall", "Q3"] <- as.character("CRESCENT")
cs[cs$Q3 == "Warneford Hall", "Q3"] <- as.character("WARNEFORD")
#Combine columns to produce matchable room string
cs$site_room <- paste(cs$Q3, cs$Q4, cs$Q21)
#Remove spaces for matching
cs$site_room <- gsub('\\s+', '', cs$site_room)
#Convert to factor
cs$site_room <- as_factor(cs$site_room)

#Convert char strings to numerics for col 15-111 (survey main body)
cs [,15:111] <- as_tibble(
  sapply(cs[,15:111], as.numeric, USE.NAMES = FALSE))
cs [,115] <- as_tibble(
  sapply(cs[,115], as.numeric, USE.NAMES = FALSE))

#Define function to reverse scored items
reverse5 <- function (x) recode(x,'5' = 1, '4' = 2, `2` = 4, '1'=5) 
reverse7 <- function (x) recode(x, '3'=-3, `2` = -2, `1` = -1, `-1` = 1, `-2` = 2, '-3'=3) 

#Apply reverse scoring to NEP
cs[c(16, 18, 20, 22, 24, 26, 28)] <- lapply (
  cs[c(16, 18, 20, 22, 24, 26, 28)], reverse7)

#Apply reverse scoring to EAI
#Original: cs[c(31,33,35,37,38,41,42,44,47,49,51,53)] <- lapply (cs[c(31,33,35,37,38,41,42,44,47,49,51,53)], reverse7)
cs[c(31,33,35,36,39,41,43,44,46,48,51,53)] <- lapply (
  cs[c(31,33,35,36,39,41,43,44,46,48,51,53)], reverse7)

#Apply reverse scoring to BSCS
cs[c(100,101,102,103,105,107,108,110,111)] <- lapply (
  cs[c(100,101,102,103,105,107,108,110,111)], reverse5)

#Compute EAI mean
cs <- cs %>% rowwise() %>% mutate(EAI_mean = mean(c(
  Q6_1, Q6_2, Q6_3, Q6_4, Q6_5, Q6_7, Q6_8, Q6_9, Q6_10, Q6_11, Q6_12, Q6_13,
  Q6_14, Q6_15, Q6_16, Q6_17, Q6_18, Q6_19, Q6_20, Q6_21, Q6_22, Q6_23, Q6_24), na.rm = TRUE)) %>% ungroup()

#Create scales
NEP <- cs %>% select(Q5_1:Q5_15)
EAI <- cs %>% select(Q6_1:Q6_24)
BSCS <- cs %>% select(Q11_1:Q11_13)
likelyPEB <- cs %>% select(Q7_1:Q7_22)
thermo_moral <- cs %>% select(Q8_7:Q8_9)
moral_ascoop <- cs %>% select(Q9_1:Q9_7)
moral_found <- cs %>% select(Q10_1:Q10_7)

#Create Activist and Pragmatist variables from likely PEB scale
cs <- cs %>% rowwise() %>% mutate(
  PEB_activist = mean(c(Q7_2, Q7_3, Q7_4, Q7_5, Q7_6, Q7_8, Q7_9, Q7_10, Q7_11), na.rm = TRUE))
cs <- cs %>% rowwise() %>% mutate(
  PEB_pragmatist = mean(c(
    Q7_12, Q7_13, Q7_14, Q7_15, Q7_16, Q7_17, Q7_18, Q7_19, Q7_20, Q7_21, Q7_22), na.rm = TRUE))

#Calculate overall scores for NEP, BSCS, likelyPEB
#creates vector of means..
cs <- cbind(cs, NEP_mean = rowMeans(NEP, na.rm = TRUE))
cs <- cbind(cs, likelyPEB_mean = rowMeans(likelyPEB, na.rm = TRUE))
cs <- cbind(cs, BSCS_mean = rowMeans(BSCS, na.rm = TRUE))
cs <- cbind(cs, thermo_moral_mean = rowMeans(thermo_moral, na.rm = TRUE))
cs <- cbind(cs, MAC_mean = rowMeans(moral_ascoop, na.rm = TRUE))
cs <- cbind(cs, MFT_mean = rowMeans(moral_found, na.rm = TRUE))

#Rename column names to descriptives: cs %>% rename(new = old)
cs <- cs %>% rename('Political orientation' = Q35_1)
cs <- cs %>% rename('Habit' = Q8_2)
cs <- cs %>% rename('SocialNorm' = Q8_3)
cs <- cs %>% rename('PBC' = Q8_5)
cs <- cs %>% rename('AwarenessConsequences' = Q8_1)
cs <- cs %>% rename('Intention' = Q8_6)
cs <- cs %>% rename('AscriptionResponsibility' = Q8_4)

#Replace 0's with NA in Age
cs$Q34[cs$Q34 == 0] <- NA

#Centre Age
cs$Q34 <- cs$Q34 - mean(cs$Q34, na.rm = TRUE)

#LOAD IN THE THERMOSTAT DATA

#Read in the Irus data (hourly, without interactions)
irus_data <- vroom("IrusData - Energy data Crescent and Warneford.csv",
  col_names = TRUE, col_select = c(1:5, 7, 10, 11, 25, 26))

#Filter for student room heaters only (takes out water heaters, kitchens, offices etc)
irus_data <- irus_data %>%
  filter(Type == "Room Heater", Name != "Office", nchar(Name) <= 6) %>%
  arrange(Name)

irus_data$Site <- as.factor(irus_data$Site)

#Load external temperature data (source: Weather Online)
external_temp <- tibble(fread("Oxford temp data.csv") %>%
  rename(Ext_temp_celsius = `Temp 2m [C]`) %>%
  select(Date, Ext_temp_celsius))
external_temp$Date <- as.Date(external_temp$Date, "%d/%m/%Y")

irus_data <- left_join(irus_data, external_temp, by = "Date")

#Merge the Site and Room Name fields
irus_data$site_room <- paste(irus_data$Site, irus_data$Name)

#Remove any spaces (to ensure matching)
irus_data$site_room <- gsub('\\s+', '', irus_data$site_room)

#Merge the date and time fields
irus_data$date_time <- fastPOSIXct(paste(irus_data$Date, irus_data$Time))

#Convert rooms to factors (for graphing)
irus_data$site_room <- as.factor(irus_data$site_room)

#Add daily mean setpoint per room and daily average per room into dataframe

irus_data <- irus_data %>% group_by(site_room, Date) %>% 
  mutate(daily_mean_sp = mean(Setpoint, na.rm = TRUE),
         daily_airtemp = mean(`Temp Air`, na.rm = TRUE))

irus_data <- left_join(irus_data, irus_data %>% 
                         group_by(site_room, Date) %>% 
                         filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
                         filter(Setpoint != 19) %>% mutate(daily_mean_sp_excdflt = mean(
                           Setpoint, na.rm = TRUE)))

irus_data <- left_join(irus_data, irus_data %>% 
                         group_by(site_room) %>% 
                         filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
                         filter(Setpoint != 19) %>% mutate(mean_sp_excdflt = mean(
                           Setpoint, na.rm = TRUE)))

#HYPOTHESIS 4 - add Before & After tags

irus_data$intervention <- NA
attach(irus_data)
irus_data$intervention[Date < as.Date("2020-02-14")] <- "Before"
irus_data$intervention[Date > as.Date("2020-02-14")] <- "After"
detach(irus_data)

#Add EXCLUDE filter for peaks
exclude <- irus_data %>% filter((Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) |
(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01"))) %>%
  group_by(date_time ,site_room ) %>%
  summarise(temp = Setpoint) %>%  summarise(temp = mean(temp, na.rm = TRUE)) %>% 
  arrange(desc(temp)) %>% filter (temp > 20) %>% pull(date_time)

# Add EXCLUDE flag to Irus dataframe - 0 = ones to ignore; 1 = ones to keep
irus_data <- irus_data %>% ungroup() %>% mutate(exclude = (ifelse(irus_data$date_time %in% exclude, 0, 1)))



#Calc mean room temp before and after posters (14th Feb) for each room & append to irus_data
irus_data <- left_join (irus_data, irus_data %>% 
  filter (Date > as.Date("2020-01-30") & Date < as.Date(  "2020-02-14")) %>% 
  group_by(site_room) %>% 
  summarise(avg_setpoint_before = mean(Setpoint)), by = "site_room")

irus_data <- left_join (irus_data, irus_data %>%
 filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>%
   group_by(site_room) %>%
   summarise(avg_setpoint_after = mean(Setpoint)), by = "site_room")

#Calculate with cleaned data - exclude peaks
irus_data <- left_join (irus_data, irus_data %>% 
  filter (Date > as.Date("2020-01-30") & Date < as.Date(  "2020-02-14")) %>% filter (exclude == 1) %>%
  group_by(site_room) %>% 
  summarise(avg_setpoint_beforeCL = (mean(Setpoint) - 19)), by = "site_room")

irus_data <- left_join (irus_data, irus_data %>%
 filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>% filter (exclude == 1) %>%
   group_by(site_room) %>%
   summarise(avg_setpoint_afterCL = (mean(Setpoint) - 19)), by = "site_room")

irus_data <- left_join (irus_data, irus_data %>%
 filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-03-01")) %>% filter (exclude == 1) %>%
   group_by(site_room) %>%
   summarise(avg_setpointCL = (mean(Setpoint) - 19)), by = "site_room")

 
#Calculate before and after average thermostat set points EXC. default settings + add to irus_data
irus_data <- left_join (irus_data, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>% 
    filter(Setpoint != 19) %>% 
  filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_before_excdflt = mean(Setpoint)), by = "site_room")

irus_data <- left_join (irus_data, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_after_excdflt = mean(Setpoint)), by = "site_room")


#Add EXC defaults, EXC peaks data to Irus
irus_data <- left_join (irus_data, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>% 
    filter(Setpoint != 19) %>% 
  filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>% filter(exclude == 1) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_before_excdfltCL = mean(Setpoint)), by = "site_room")

irus_data <- left_join (irus_data, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>% 
  filter(exclude == 1) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_after_excdfltCL = (mean(Setpoint)-19)), by = "site_room")

#MEANS
irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>% 
    filter(Setpoint != 19) %>% 
  filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>% filter(exclude == 1) %>% 
  summarise(avg_sp_before_excdfltCL = (mean(Setpoint)-19)) %>% as.data.frame()

irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>% 
    filter(Setpoint != 19) %>% 
  filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>% filter(exclude == 1) %>% 
  summarise(avg_sp_before_excdfltCL = (mean(Setpoint)-19)) %>% as.data.frame()

irus_data <- irus_data %>% mutate (thermo_change_excdflt = avg_sp_after_excdflt - avg_sp_before_excdflt)

#Calculate number of settings below 19 degrees, before and after 14th Feb (posters date)

#Add thermostat data inc defaults to CS
cs <- left_join(cs, irus_data %>% 
    filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>% 
    group_by(site_room) %>% 
    summarise(avg_setpoint_before = mean(Setpoint)), by = "site_room")

cs <- left_join(cs, irus_data %>% 
                  filter(Date > as.Date("2020-02-14") & Date < as.Date(  "2020-03-01")) %>%
                  group_by(site_room) %>%
                  summarise(avg_setpoint_after = mean(Setpoint)), by = "site_room")


cs <- left_join(cs, irus_data %>% 
    filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>% filter(exclude == 1) %>%
    group_by(site_room) %>% 
    summarise(avg_setpoint_beforeCL = (mean(Setpoint)-19)), by = "site_room")

cs <- left_join(cs, irus_data %>% 
                  filter(Date > as.Date("2020-02-14") & Date < as.Date(  "2020-03-01")) %>% filter(exclude == 1) %>%
                  group_by(site_room) %>%
                  summarise(avg_setpoint_afterCL = (mean(Setpoint)-19)), by = "site_room")

cs <- left_join(cs, irus_data %>% 
                  filter(Date > as.Date("2020-01-30") & Date < as.Date(  "2020-03-01")) %>% filter(exclude == 1) %>%
                  group_by(site_room) %>%
                  summarise(avg_setpointCL = (mean(Setpoint)-19)), by = "site_room")


#Add thermostat data exc defaults

cs <- left_join (cs, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_before_excdflt = mean(Setpoint)), by = "site_room")

cs <- left_join (cs, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_after_excdflt = mean(Setpoint)), by = "site_room")

cs <- cs %>% mutate(avg_sp_before_excdflt19 = avg_sp_before_excdflt - 19,
                    avg_sp_after_excdflt19 = avg_sp_after_excdflt - 19)

#Add data exc dflt & exc peaks (cleaned)
cs <- left_join (cs, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-02-14")) %>%
  filter(exclude == 1) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_before_excdfltCL = (mean(Setpoint)-19)), by = "site_room")

cs <- left_join (cs, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-02-14") & Date < as.Date("2020-03-01")) %>%
  filter(exclude ==1) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_after_excdfltCL = (mean(Setpoint)-19)), by = "site_room")

cs <- left_join (cs, irus_data %>% 
  filter(!(Setpoint == 21 & hour(date_time) >= 7 & hour(date_time) <= 10)) %>%
filter(Setpoint != 19) %>% filter(Date > as.Date("2020-01-30") & Date < as.Date("2020-03-01")) %>%
  filter(exclude ==1) %>%
  group_by(site_room) %>% 
  summarise(avg_sp_overall_excdfltCL = (mean(Setpoint)-19)), by = "site_room")

#Add change variable
cs <- cs %>% mutate(thermo_changeCL = avg_setpoint_afterCL - avg_setpoint_beforeCL)
cs <- cs %>% mutate (thermo_change_excdfltCL = avg_sp_after_excdfltCL - avg_sp_before_excdfltCL)

#Standardise key variables
cs <- cs %>% mutate(likelyPEB_mean_sz = as.numeric(scale(likelyPEB_mean)))
cs <- cs %>% mutate(EAI_mean_sz = as.numeric(scale(EAI_mean)))
cs <- cs %>% mutate(NEP_mean_sz = as.numeric(scale(NEP_mean)))
cs <- cs %>% mutate(PEB_activist_sz = as.numeric(scale(PEB_activist)))
cs <- cs %>% mutate(PEB_pragmatist_sz = as.numeric(scale(PEB_pragmatist)))
cs <- cs %>% mutate(thermo_moral_mean_sz = as.numeric(scale(thermo_moral_mean)))
cs <- cs %>% mutate(MAC_mean_sz = as.numeric(scale(MAC_mean)))
cs <- cs %>% mutate(MFT_mean_sz = as.numeric(scale(MFT_mean)))
# cs <- cs %>% mutate(sub19_before_sz = as.numeric(scale(sub19_before)))
# cs <- cs %>% mutate(sub19_after_sz = as.numeric(scale(sub19_after)))
cs <- cs %>% mutate(avg_setpoint_before_sz = as.numeric(scale(avg_setpoint_before)))
cs <- cs %>% mutate(avg_setpoint_after_sz = as.numeric(scale(avg_setpoint_after)))
cs <- cs %>% mutate(avg_sp_before_excdflt_sz = as.numeric(scale(avg_sp_before_excdflt)))
cs <- cs %>% mutate(avg_sp_after_excdflt_sz = as.numeric(scale(avg_sp_after_excdflt)))
cs <- cs %>% mutate(thermo_changeCL_sz = as.numeric(scale(thermo_changeCL)))
# cs <- cs %>% mutate(sub19_change_sz = as.numeric(scale(sub19_change)))
cs <- cs %>% mutate(thermo_change_excdfltCL_sz = as.numeric(scale(thermo_change_excdfltCL)))
cs <- cs %>% mutate(AwarenessConsequences_sz = as.numeric(scale(AwarenessConsequences)))
cs <- cs %>% mutate(Habit_sz = as.numeric(scale(Habit)))
cs <- cs %>% mutate(Intention_sz = as.numeric(scale(Intention)))
cs <- cs %>% mutate(SocialNorm_sz = as.numeric(scale(SocialNorm)))
cs <- cs %>% mutate(AscriptionResponsibility_sz = as.numeric(scale(AscriptionResponsibility)))
cs <- cs %>% mutate(PBC_sz = as.numeric(scale(PBC)))
cs <- cs %>% mutate(BSCS_mean_sz = as.numeric(scale(BSCS_mean)))
cs <- cs %>% mutate(PoliticalOrientation_sz = as.numeric(scale(`Political orientation`)))

```

## EXPORT FOR MODELLING
```{r}
# main data file for longitudinal modelling (LARGE; 700k + rows)
write.csv(irus_data, file = "AdamIrusdata.csv")

# data file for matching effect to rooms (Small; 88 rows)
adam_data_cleaned <-left_join(cs, irus_data %>% filter(site_room %in% c(cs$site_room)) %>% filter (exclude == 1) %>%
    group_by(site_room, Date) %>% summarise(daily_mean_sp = mean(Setpoint, na.rm = TRUE), daily_airtemp = mean(
       `Temp Air`, na.rm = TRUE), daily_mean_sp_excdflt = mean(daily_mean_sp_excdflt, na.rm = TRUE),
       external = mean(Ext_temp_celsius)),
    by = "site_room")

write.csv(adam_data_cleaned, file = "Adam4nopeaks.csv")
```

## CREATE DATA-FRAME for modelling
```{r}
df <- irus_data %>%
  filter(Date >= as.Date("2020-02-01")) %>%  #dropping all data points before Feb 1
  filter(Date <= as.Date("2020-02-29")) %>%
  mutate(TEMP.C = TEMP-19) %>% #Centering TEMP with defaults on 19
  mutate(EXTERNAL.Z = (Ext_temp_celsius - mean(Ext_temp_celsius,  na.rm=T))/sd(Ext_temp_celsius, na.rm=T)) #standardise external temperature

